import Navbar from "./components/nav/navbar";
import "./globals.css";


export const metadata = {
  title: "Elnaggar Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
