import Navbar from "./components/nav/navbar";
import PortableMenu from "./components/portablemenu/portablemenu";
import "./globals.css";


export const metadata = {
  title: "Elnaggar Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <PortableMenu></PortableMenu>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
